### ISSUE TITLE
requests with 0 events

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#11]
Adrian @AdrianAlan  , found that requests in submitted which don't have any event produced yet, are not properly monitor-able because stats miss info about them - such info appears as soon as the first file is produced.

+ RunIISpring15Digi74 
   is currently (Mon Apr 27 18:51:35 CEST 2015) showing this problem, see the two screenshots

+ Fall14DR73
   is where the issue was noted first
![screen shot 2015-04-27 at 18 50 45](https://cloud.githubusercontent.com/assets/4729828/7352801/edd06dba-ed0e-11e4-86ac-3dcd3b6a2f5c.png)
![screen shot 2015-04-27 at 18 51 11](https://cloud.githubusercontent.com/assets/4729828/7352803/efadf1d4-ed0e-11e4-831d-8d569e1b46cb.png)

![screen shot 2015-04-27 at 18 51 11](https://cloud.githubusercontent.com/assets/4729828/7352828/0f22d0ac-ed0f-11e4-80eb-e49fbe9e369f.png)
![screen shot 2015-04-27 at 18 50 45](https://cloud.githubusercontent.com/assets/4729828/7352829/0f24ac2e-ed0f-11e4-89c1-1de4c5eee45f.png)

**Comment by AdrianAlan** [comment]
I'll patch this for tomorrow's pull

**Comment by franzoni** [comment]
for my understanding: is the missing information to be made available by modifying stats or pmp  (or both)?

**Comment by AdrianAlan** [comment]
just pmp

**Comment by AdrianAlan** [comment]
if output dataset is not set, the number of expected events is added to historical plot, however number of produced events is forced to 0 - this ensures consistency between historical and present chart
