### ISSUE TITLE
colouring of STATUS in histograms

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#2]
hello @AdrianAlan,
would it be possible that the colours assigned to the request STATUS be defined and stay always the same ?
(along the lines of what you've already done for the PWG)
This would make it clear comparing different plots and would, in the long run, establish a consuetude where people know at a glance what a color means.
Thanks!

**Comment by AdrianAlan** [comment]
This was already implemented
https://github.com/cms-PdmV/pmp/blob/master/pmp/static/js/charts.js#L668
