### ISSUE TITLE
search by chained campaign

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#20]
hi 

https://cms-pdmv-int.cern.ch/pmp/present?r=chain_RunIIWinter15GS_flowRunIISpring15DR74AsymptFlat0to50bx50RawReco

I'd expect to see members of that chain   chain_RunIIWinter15GS_flowRunIISpring15DR74AsymptFlat0to50bx50RawReco  , 

what am I doing wrong ?

**Comment by AdrianAlan** [comment]
Chain input is available only in growing view.
Please: http://tinyurl.com/nzyybjl

**Comment by AdrianAlan** [comment]
Added here:
https://twiki.cern.ch/twiki/bin/view/CMS/PdmVpMp#Why_does_the_Present_Statistics
