### ISSUE TITLE
Download buttons do not work

### ISSUE THREAD

**Issue by jacobwalkr** [cms-PdmV/pmp#28]
The "Download" buttons (offering PDF, JPEG and PNG downloads of the data currently represented on-screen) do not work.

Clicking any of the buttons produces this error: `414 Request-URI Too Large`.

**Comment by anorkus** [comment]
GET method must be dropped. POST should be used instead while sending bigger data

**Comment by AdrianAlan** [comment]
Fixed in 9b0b047d8579a34b542c1df526d50f5d5282ff57
