### ISSUE TITLE
prepID needs take-out-put-back-in selection field to be correctly displayed

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#29]
example: 

http://pmp-dummy.cern.ch/present?r=B2G-Fall13-00050&p=0,0,3,1,0,0,0,0&m=false&c=true&t=false&x=,&w=B2G&s=done

note this is "chain mode" for a single request

**Comment by pdmvserv** [comment]
Steps to reproduce:
1. Load a request in Present Announced mode.
2. Display chains
3. Add PREPID to Grouping.
4. Remove MEMBER_OF_CHAIN
5. Be confused
--
Jacob Walker
PH-CMG-CO
CERN, bldg. 40/3-A15
CH-1211 Geneva 23
On 21 Oct 2015 12:23, Giovanni Franzoni <notifications@github.com> wrote:example: 

http://pmp-dummy.cern.ch/present?r=B2G-Fall13-00050&p=0,0,3,1,0,0,0,0&m=false&c=true&t=false&x=,&w=B2G&s=done

note this is "chain mode" for a single request

**Comment by jacobwalkr** [comment]
Steps to reproduce:

1. Load a request in Present Announced mode.
2. Display chains
3. Add PREPID to Grouping.
4. Remove MEMBER_OF_CHAIN
5. Be confused

**Comment by AdrianAlan** [comment]
It's not only prepid - any other selection has this problem, same with non growing mode. Probably 
https://github.com/cms-PdmV/pmp/blob/master/pmp/static/js/directives/present-column.js#L260
Takes empty array as grouping
