### ISSUE TITLE
repetition of items in plot legend 

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#3]
Hello @AdrianAlan,

in this view:

https://cms-pdmv.cern.ch/pmp/present?r=Summer12&p=1,0,3,0,0,0,0,0&t=false&m=true&x=,&w=B2G,BPH,EWK,EXO,FSQ,HIG,JME,QCD,SMP,SUS,TOP,FWD,EGM,MUO,BTV&ne=true&va=true&de=true&ap=true&su=true&do=true&up=true

if in FILTER => STATUS FILTER I un-selected any of the three "defined new upcoming", in the color legenda an additional "approved" item appears.

A little pmp glitch ? Or something funky in the content coming the db ?

Cheers,
g.

**Comment by AdrianAlan** [comment]
Frontend bug
