### ISSUE TITLE
Inconsistency historical expected vs present announced submitted

### ISSUE THREAD

**Issue by AdrianAlan** [cms-PdmV/pmp#33]
Some workflows are remaining with empty monitor_details on stats (when status acquired), making expected events in historical 0. This is of course inconsistent with present announced events (submitted status only)
Proposed fix: make a dummy entry in fetchd around line 
https://github.com/cms-PdmV/pmp/blob/master/fetchd/fetchd.py#L184
if 'pdmv_monitor_history' and 'pdvm_monitor_history' are not in data:
    data['pdmv_monitor_history'] = [{'pdmv_evts_in_DAS':0, 'pdmv_monitor_time':current_time, 'pdmv_open_evts_in_DAS':0}]

this fake field will be updated while workflow leaves acquired.
make sure that current_time is in the right form, check in db

**Comment by jacobwalkr** [comment]
Waiting on pull request #34

**Comment by jacobwalkr** [comment]
Need to run integrity tests on my local machine to verify, when `fetchd.py` has finished updating my local indexes. This can't be easily tested on `dev`, apparently, because `dev` uses a development version of the Elastic indexes which won't pass the integrity test.
