### ISSUE TITLE
pMp prod update periodically fails to get SSO cookie

### ISSUE THREAD

**Issue by jacobwalkr** [cms-PdmV/pmp#35]
Every other day or so, the Jenkins job "pMp prod Update" fails, with an error such as this one:

```
+ python /home/pmp/fetchd/fetchd.py chained_requests
INFO:root:2015-12-04 16:08:11.998884 Getting SSO Cookie
Error: Cannot authenticate to: https://cms-pdmv.cern.ch/mcm/ : Timeout was reached (Operation timed out after 30000 milliseconds with 0 bytes received)

INFO:root:2015-12-04 16:08:42.661728 Updating since 341270
Status: 302/n<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://login.cern.ch/adfs/ls/?wa=wsignin1.0&amp;wreply=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wct=2015-12-04T15%3A08%3A42Z&amp;wtrealm=https%3A%2F%2Fcms-pdmv.cern.ch%2FShibboleth.sso%2FADFS&amp;wctx=cookie%3A1449241722_e1d6">here</a>.</p>
</body></html>

Traceback (most recent call last):
  File "/home/pmp/fetchd/fetchd.py", line 170, in <module>
    for r, deleted in get_changes(UTL, CFG):
  File "/home/pmp/fetchd/fetchd.py", line 131, in get_changes
    cookie=cfg.cookie)
TypeError: 'NoneType' object is not iterable
Build step 'Execute shell' marked build as failure
```

There must be a way to detect this problem and fix it at runtime, given that the job is always successfully retried soon afterwards. I'm getting tired of the emails.

**Comment by jacobwalkr** [comment]
This might well have something to do with the curl timeout. The issue increased in frequency over the closure and occurs only for the pdmvserv account. The issue is currently monkey-patched (and not even reliably) by increasing `CURLOPT_TIMEOUT` in `/usr/share/perl5/vendor_perl/WWW/CERNSSO/Auth.pm` as in SNow ticket [RQF0481926](https://cern.service-now.com/service-portal/view-request.do?n=RQF0481926).

**Comment by jacobwalkr** [comment]
Increased timeout to 5 minutes and almost all jobs succeed now. Funny.

Hopefully something comes of this: https://cern.service-now.com/service-portal/view-request.do?n=RQF0538677

**Comment by jacobwalkr** [comment]
Partly resolved by @anorkus and Andreas by fixing the issue of cookies taking a million years to get. The issue still stands that the cookie becomes invalid in the middle of the script, and so if there are a lot of records to update (as on `pMp dev update` at the time of writing), there will be weeks of failed jobs.

**Comment by anorkus** [comment]
there should be either a retry and cookie regeneration when response code is 302 -> this should lower the -prod update crashing

**Comment by jacobwalkr** [comment]
This is what I'm thinking. Retry once or twice and THEN fail.
