### ISSUE TITLE
Missing legend in historical report on firefox

### ISSUE THREAD

**Issue by cerminar** [cms-PdmV/pmp#41]
The historical report, from time to time, misses the legend displaying the # of events in each category (see attached image). The problem, as far as I can tell, appears only on firefox and not every time I access the page.

Cheers,
G
![screen shot 2015-12-15 at 2 19 01 pm](https://cloud.githubusercontent.com/assets/4802196/11811669/2f40eea8-a337-11e5-94b3-67f23b3b82c8.png)

**Comment by jacobwalkr** [comment]
These are being hidden on "small" and "extra-small" screens. I'll get to it - in the meantime, you should be able to see them if you make your window a bit wider :)
