### ISSUE TITLE
"unselect all" in the "FILTER" panel

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#43]
willing to filter on a single PWG,
it would be useful to have the functionality of unselecting all the PWG's, 
to go straight to the ticking of the desired PWG
(instead of deselecting one-by-one which takes time, since the rendering of the plots is refreshed at each transition)

**Comment by jacobwalkr** [comment]
Got some tasty buttons in that filter panel now.

![Hodgens off Bones throwing his arms in the air and shouting "Yes!"](https://media.giphy.com/media/oa88mwu1sDp72/giphy.gif)
