### ISSUE TITLE
Orphaned "new" requests skew numbers in pMp campaign plots

### ISSUE THREAD

**Issue by jacobwalkr** [cms-PdmV/pmp#48]
There are requests with status "new" that are created in McM and then forgotten about. There should be some way of removing these from the plot to get more relevant information.

**Comment by jacobwalkr** [comment]
@franzoni @srimanob Can you confirm that hiding unchained requests with status "new" would resolve this? If so, can you give me an example of such a request? I can't seem to find one.

**Comment by srimanob** [comment]
@jacobwalkr 
This should be an example (RunIIWinter15wmLHE campaign)
https://cms-pdmv.cern.ch/mcm/requests?prepid=TOP-RunIIWinter15wmLHE-00046&page=0

**Comment by jacobwalkr** [comment]
@srimanob Thanks. Are we filtering these out in Historical mode, too?

**Comment by jacobwalkr** [comment]
This fix has been deployed live.

**Comment by jacobwalkr** [comment]
To clarify: this is not actually live - got excited and merged to master, but it is not running on prod, pending testing and approval from the prod e-group next week :)

**Comment by jacobwalkr** [comment]
Now it's live! Informing hn-cms-prep-ops@cern.ch
