### ISSUE TITLE
display of last data update

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#5]
hi @AdrianAlan, 
we'd like to have:

   the time of last update of the data available to pMp 

available to the user, displayable upon request, together with the current date.
Is the time o the elasticsearch update sufficient ? Does the stats/mcm updates latency contribute significantly ?

Cheers,
g.

**Comment by AdrianAlan** [comment]
The solution in place should be enough. Right now it is showing last update to elastic. Pulled to prod.
