### ISSUE TITLE
"Load all" URL contains an explicit list of campaigns to include

### ISSUE THREAD

**Issue by jacobwalkr** [cms-PdmV/pmp#50]
This becomes out-of-date as soon as a new campaign is created, because that new campaign will not be included in this list.

**Comment by anorkus** [comment]
but historically it makes sense if you want to see all campaigns which existed at certain point

**Comment by jacobwalkr** [comment]
This is also true.

**Comment by jacobwalkr** [comment]
We'll have to find out if that's a common use case. Perhaps if it is, we could add a "load all *to date*" option in advanced, which includes an explicit list.

**Comment by jacobwalkr** [comment]
Released on 30 Aug!
