### ISSUE TITLE
No data visible in image download

### ISSUE THREAD

**Issue by intrepid42** [cms-PdmV/pmp#52]
Hi, I would like to get an image from, e.g., https://cms-pdmv.cern.ch/pmp/historical?r=RunIISummer15GS&p=100&t=false&y=false&x=,&w=TOP&s=done,submitted

The downloaded image shows the correct axes but no data:
![pmp_2016-02-02 09 37 22 068514](https://cloud.githubusercontent.com/assets/1311783/12743825/c184542e-c990-11e5-9872-2d4b98255b25.png)

**Comment by jacobwalkr** [comment]
Oh dear. This seems to be an issue with Historical mode. Have you successfully downloaded an image of a Historical plot in the past?

**Comment by intrepid42** [comment]
No, I just tried for the first time after I saw these plots in the [PC slides](https://indico.cern.ch/event/477409/contribution/0/attachments/1216198/1778851/PC_meeting_slides_25Jan2016.pdf) (p. 4-6).

**Comment by jacobwalkr** [comment]
Interesting. The plots in those slides seem to be screenshots of the interface, as opposed to images downloaded using the Download buttons.

**Comment by intrepid42** [comment]
Probably. I had to do the same now but it is really an ugly workaround :D

**Comment by jacobwalkr** [comment]
I completely agree!
