### ISSUE TITLE
serialisation of the button mcm => pmp

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#55]
the functionality in slide 3 of the talk

to be extended to load in pmp a set of requests, the same set which is presented in an mcm page

**Comment by jacobwalkr** [comment]
@anorkus Something for McM?

**Comment by anorkus** [comment]
emm yea: https://github.com/cms-PdmV/cmsPdmV/issues/821

**Comment by jacobwalkr** [comment]
Cool!
