### ISSUE TITLE
upcoming column in campaign tables

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#6]
Hello @AdrianAlan 

the upcoming column in campaign tables shown at the bottom of the pMp pages shows no number.

Can we fix that ? Please note  (expected events of input req)*eff in: https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVpMp

cheers,
g.

**Comment by AdrianAlan** [comment]
Fixed in prod
