### ISSUE TITLE
reflect in url the "SELECTIONS COLORING STACKING GROUPING"

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#63]
in present mode
one can move around the "bricks" across:
{ SELECTIONS COLORING STACKING GROUPING }
in order to change the representation. 

IT would be great to have this reflect in the url.

**Comment by jacobwalkr** [comment]
This is reflected in the field that contains comma-separated integers - I can't remember what it's called. Perhaps you could do some magic to make it human-readable, but it is there.

**Comment by jacobwalkr** [comment]
Lines 67-120 of the present controller in Angular:

https://github.com/cms-PdmV/pmp/blob/master/pmp/static/js/controllers/present.js#L67

**Comment by franzoni** [comment]
this feature would remain great to have
is it in any work plan
( priority of this wish remains low to middle )

**Comment by franzoni** [comment]
Hi @justinasr was this topic addressed 😉?

**Comment by anorkus** [comment]
hi, yes in  ffc27f2 as this issue was auto-closed with that commit
