### ISSUE TITLE
feature suggestion: linkable list of MCM entries in the list below summary plots

### ISSUE THREAD

**Issue by govoni** [cms-PdmV/pmp#66]
Hello guys,

while browsing requests in this output:

https://cms-pdmv.cern.ch/pmp/historical?r=RunIISummer16DR80Premix

I realised that it might be useful to make the list of MCM tasks linkable, to see what is a single request.
Do you think that this feature could be implemented?

**Comment by anorkus** [comment]
by tasks you mean the requests listed in submitted status?

**Comment by govoni** [comment]
yes, the ones besides the completion bar. It should be enough to add a fixed text to the created page, embedding each the request name, I guess.
