### ISSUE TITLE
List of requests on status submitted: better readibility

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#68]
When the list of requests is very long
matching a progress bar and the PD name is a bit difficult

Can we make the visual impact easier:
+ either by spacing 'progress bar +PD' one from the next 
+ or putting progress bar and the PD on the same line

**Comment by franzoni** [comment]
Hi @justinasr
Thanks for working on this.
What does the page look like now?
Can you include a screenshot?

**Comment by justinasr** [comment]
Hello,
Every other line is different color than the background.
Background of a line also changes to light gray when you hover mouse over that entry.
Example in dev environment (I don't know if you have access): https://cms-pdmv-dev.cern.ch/pmp/historical?r=RunIIFall17wmLHEGS

![screenshot](https://user-images.githubusercontent.com/9316557/32774559-f07360c0-c92c-11e7-8cc5-1aa66dfad4d5.png)

**Comment by franzoni** [comment]
Very useful, thanks!
