### ISSUE TITLE
Update max events upon force completion

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#69]
When a request gets force completed, the target number of events ( grey ) should decrease to the value at the end of the force completion.

This behaviour would allow monitoring the campaigns meaningfully: ie the the campaign is complete when the orange/ blue reach the grey 
( While at the moment we loose the capability of monitoring campaigns with forced closures)

**Comment by anorkus** [comment]
pmp indexes the total_events (target) from McM, so this change would make sense on McM side. Then  a feature showing original/intended  total_events of request/campaign is a good thing.

**Comment by franzoni** [comment]
thanks @anorkus I appreciate the complexity.
We don't want to modify the original total_events in mcm, that's a sure thing.

Can you / @justinasr think of a proposal on how to:
1) retrieve the number of events reached upon force-completion, and 
2) have such number reach the pmp elastic ?

Obviously not a minor tweak. Still, this feature would help hugely on the monitoring, especially of campaigns which are troublesome.

@GurpreetSinghChahal @fabozzi @klute
