### ISSUE TITLE
numbers human readable in tables

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#7]
hi @AdrianAlan ,

the easies way of reading the numbers in the table is 1.34M 1.20k, as you get in some linux commands with -h . Keeping 3 significant figures is the proposed criterion, and determines wether G, M or k are to be used. 
We want to have a flag in the "advanced" to flip to displaying the exact numbers, where the plain integer is shown with all its figures.

Cheers, g

**Comment by AdrianAlan** [comment]
Fixed in prod
