### ISSUE TITLE
table and pie-chart switching to "[number of] requests" 

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#72]
There are buttons to modify the values displayed by the histograms in Present Mode
to "number of requests" or "seconds".

Can we have the pie chart and the tables also switch to "number of requests" or "seconds",
consistently ?
See the attached screenshot, showing that currently  when "number of requests" is on
the pie chart and table still show "number of events"
LOW PRIO.

<img width="871" alt="screen shot 2018-05-08 at 11 15 56" src="https://user-images.githubusercontent.com/4729828/39748933-bc16cc0e-52b1-11e8-90d5-51d4568a4354.png">

**Comment by justinasr** [comment]
Done.
