### ISSUE TITLE
update requests even before running ( especially priority)

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#75]
this is more of a request to stats db, pmp will act as a consequence.

Parameters of a request get updated if 5% of its expected events appear in dbs.
Can we remove such conditional to "5% events in dbs" ? 

Concrete and essential use case:
1 . we submit a request with priority X --> stats pics up prio X and pmp displays it
2 . we re-organize priorities and X get changed to Y
3 . up to the moment the request receives 5% of the events, prio is still displayed as X

3. renders the monitoring unreliable and ineffective: especially in complex priority migration and mid term planning, most re-prioritized jobs may not start running for days, and in the meantime the monitoring is inaccurate

**Comment by justinasr** [comment]
5% check was removed when Stats2 came into production.
