### ISSUE TITLE
Getting the historical data as a numbers

### ISSUE THREAD

**Issue by zleba** [cms-PdmV/pmp#78]
Dear authors,
is there any way how to get the historical data about the sample size from the pmp database.
The ideal would be some restful method to get the data e.g. in the json format, like:
https://cms-pdmv.cern.ch/pmp/json/historical/JME-RunIIFall18wmLHEGS-00001
Is there anything like that?
Thanks a lot,
Radek

**Comment by justinasr** [comment]
Hello,

Are you looking for something like this: https://cms-pdmv.cern.ch/pmp/api/JME-RunIIFall18wmLHEGS-00001/historical/100/,/all/all ? pMp uses this exact data to plot the graph.

Justinas R.

**Comment by zleba** [comment]
Great, that's exactly what I need.
Thanks a lot.
Radek
