### ISSUE TITLE
Shortening of URL

### ISSUE THREAD

**Issue by AdrianAlan** [cms-PdmV/pmp#8]
The copy button under share menu should make use of the CERN's URL shortening service

**Comment by AdrianAlan** [comment]
CERN's Shorten URL service seems quite a problem to implement. Creating service tickets, authentication etc. is a bit too much overhead. I used tinyurl instead, which doesn't need any auth or key

**Comment by franzoni** [comment]
Hi Adrian, have you thought carefully as to wether using an external service poses security  / royalty issues ? Is it unlimitedly for free ? Since pMp is behind SSO, I can't think of anything obvious constituting a problem... you're the computer scientist, maybe is there anything non-obvious ?

**Comment by anorkus** [comment]
hi,
the service is free. And the links it would shorten is under cern sso, so we are not exposing anything. Only reason could be that shortening service will stop existing, but same can happen with cern services also. And tinyurl was one of the original and longest lasting shortening services, so i do not see a big problem using it.

**Comment by AdrianAlan** [comment]
The only risk is what we expose in URL, which is campaigns names and PWGs. If this is confidential than we should switch to CERN Go
