### ISSUE TITLE
Show number of events of MinIAOD requests if GS don't keep output

### ISSUE THREAD

**Issue by pgunnell** [cms-PdmV/pmp#80]
Relatively high priority:

if GS requests are displayed and don't keep output, show the statistics and the progress of MiniAOD.

This is crucial because MC contacts tag only the root requests and they want to see them in pmp.

**Comment by justinasr** [comment]
This is implemented in new pMp - it estimates number of completed events from subsequent requests in chain. (DR if GS does not keep output, MiniAOD if DR does not keep, etc.)
