### ISSUE TITLE
[pmp2 feedback]: Unchained requests by status: needs be optional

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#81]
The table which appears at the bottom of "present view" 
holds too much information. 
95% of the analysis and most of the MC contacts, want to see only the summary table for requests which are already chained, and get info-overloaded if they're offered 3 tables instead of one.

I recommend that only "Chained requests by status" is shown
and the other two tables "Unchained requests by status" and "All requests by status" be shown upon toggling an option in "Options".

" (showing requests):" should be removed.

See for example https://cms-pdmv-dev.cern.ch/pmp/present?r=RunIIWinter19PFCalib17wmLHEGS, also screeenshot

![Screenshot 2019-03-28 at 12 40 52](https://user-images.githubusercontent.com/4729828/55155077-beb3c300-5156-11e9-9a7d-52f54a762529.png)

**Comment by justinasr** [comment]
Ok, I will make bottom two tables visible only if checkbox is checked.

About "(showing requests)", I am not sure whether it should be removed - it says what number is shown in the table as table can switch between requests, events and seconds by changing "Mode" at the top. At the moment, I updated the label, so it would say "(showing number of requests)".

**Comment by franzoni** [comment]
> as table can switch between requests

ok, now I understand why is there; I did not get that before.
If it was me, I would say simply "(requests)"

**Comment by justinasr** [comment]
> I recommend that only "Chained requests by status" is shown
and the other two tables "Unchained requests by status" and "All requests by status" be shown upon toggling an option in "Options".

> If it was me, I would say simply "(requests)"

Done and done!
