### ISSUE TITLE
[pmp2 feedback]: link to reqmgr for data requests (not mcm)

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#82]
would it be possible that the very useful link which appears on the left of the request list in historical view,
detects that a gioven pre-Id is for data processing (and not MC) and points to reqmgr2 (instead of mcm)

For instance in the page https://cms-pdmv-dev.cern.ch/pmp/historical?r=22Mar2019,20Mar2019 , the link behind this prepId   ReReco-Run2018D-ParkingBPH4-20Mar2019-0003  could point to  https://cmsweb.cern.ch/reqmgr2/fetch?rid=prebello_Run2018D-v1-ParkingBPH4-20Mar2019_10213_190320_220518_9441 ?

![Screenshot 2019-03-28 at 12 43 40](https://user-images.githubusercontent.com/4729828/55155234-24a04a80-5157-11e9-83d7-f36e6e039b7b.png)

**Comment by justinasr** [comment]
It is possible, but had a bug as it was supposed to point to Dmytro's page, but was incorrectly pointing to McM. I can for sure point to ReqMgr2.

**Comment by justinasr** [comment]
Links now point to ReqMgr2.
