### ISSUE TITLE
tab darkened/clicked when opening in different thread

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#83]
there are 6 buttons at the top of the pmp page 

0. pMp SE
1 . Present Statistics
2 . Historical Statistics
3 . Performance Statistics
4 . Report
5 . About

If starting from any pmp view (e.g. present, see the figure)
I open another tab by clicking Present, Historical or Performance, 
the button used remains darkened/clicked,
which is somewhat misleading.

A minor minor issue.

<img width="1248" alt="Screenshot 2019-04-09 at 11 34 35" src="https://user-images.githubusercontent.com/4729828/55789944-a1b6b280-5abb-11e9-94bf-0586f766e382.png">

**Comment by justinasr** [comment]
Note to self: bug occurs when holding ctrl and clicking on buttons at the top

**Comment by justinasr** [comment]
Fixed.
