### ISSUE TITLE
legend for present view

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#84]
It would be very helpful having a legend on top of the histogram of the present view,
defining what each color represents. 

In the case of "Color graph by" == Status
I can get the meaning of the color if I hoover over the bins (see the first image).
<img width="1248" alt="Screenshot 2019-04-09 at 11 34 35" src="https://user-images.githubusercontent.com/4729828/55790564-ed1d9080-5abc-11e9-829f-5cbf8a575c03.png">

In the case of "Color graph by" == "Total events"
I can't even understand, what the colors are.

**Comment by justinasr** [comment]
Legend is added to present statistics.
