### ISSUE TITLE
historical plot: some request show 0 expected events in the graph but nonzero in text

### ISSUE THREAD

**Issue by slava77** [cms-PdmV/pmp#88]
Here is one example for https://cms-pdmv.cern.ch/pmp/historical?r=SUS-RunIISummer16DR80Premix-00391

<img width="956" alt="Screen Shot 2019-07-16 at 10 54 41 AM" src="https://user-images.githubusercontent.com/4676718/61317711-6ca3b580-a7b8-11e9-966c-798aab86dae7.png">

**Comment by justinasr** [comment]
Hello. Was it still 0 events even if the page was refreshed? Do you have more examples of this happening?

**Comment by slava77** [comment]
It looks like the numbers became consistent in the plot after the state of the request state changed from "submitted" to "force completed".
I do not have a good/effective way to navigate to such a problem from PMP. The way I got to this one was: get "completed events" for O(100) requests in MCM, make a plot for all and compare the manually added total from the MCM table with the "expected" total in the plot.

If the origin of "completed events" in MCM and the "Expected" per-request number differs from what goes into the total of the historical pmp plot, it should be much easier to debug on your side.

**Comment by justinasr** [comment]
Hm, I believe you found a bug in pMp. When a request is force completed, it sets "expected" events in plot to last value of "done" (blue) events, so it would look like request actually completed. In this case request was already force completed, but dataset was not VALID yet, so expected events was set to 0. I'll fix it soon.
