### ISSUE TITLE
human-readble vs detailed numbers in the tables

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#9]
hi Adrian, 
it's great having "HUMAN READABLE NUMBERS" . 
I suggest that you flip the default: 
pmp to show human readable by default, 
and the tick-able option is available to read all the digits.
Cheers,
g

**Comment by franzoni** [comment]
Can we have the same human-readable setup also in the historic view ?

**Comment by AdrianAlan** [comment]
added in history plot
