### ISSUE TITLE
PMP: add priority to table

### ISSUE THREAD

**Issue by ameyer-cern** [cms-PdmV/pmp#94]
Hello Justinas,
how difficult would it be to add the request priority to the table of request in PMP?
cheers
Andreas

**Comment by justinasr** [comment]
Hello,
In historical and performance statistics tables? Not hard at all, just need to figure out how to nicely cram another column in historical table.
Justinas R.

**Comment by ameyer-cern** [comment]
Hi Justinas,
thanks! Yes in the historical table would be great!
Andreas

**Comment by justinasr** [comment]
Hello,
Added priority to historical table.
Justinas R.
